In [1]:
drinks = ["espresso", "chai", "decaf", "drip"]
caffeine = [64, 40, 0, 120]
zipped_drinks = list(zip(drinks, caffeine))
print(zipped_drinks)
drinks_dict = {drink:caff for drink, caff in zipped_drinks}
print(drinks_dict)
print(list(drinks_dict))
print(drinks_dict.keys())
print(drinks_dict.get("espresso"))
espresso = drinks_dict.pop("espresso", "NA")
print(espresso)
print(drinks_dict)
drinks_dict.update({"espresso": espresso})
print(sorted(drinks_dict))
print(drinks_dict.values())
for drinks, caffeines in drinks_dict.items():
    print("{drink} has {caffeine}mg of caffeine.".format(drink=drinks.title(), caffeine=caffeines))


[('espresso', 64), ('chai', 40), ('decaf', 0), ('drip', 120)]
{'espresso': 64, 'chai': 40, 'decaf': 0, 'drip': 120}
['espresso', 'chai', 'decaf', 'drip']
dict_keys(['espresso', 'chai', 'decaf', 'drip'])
64
64
{'chai': 40, 'decaf': 0, 'drip': 120}
['chai', 'decaf', 'drip', 'espresso']
dict_values([40, 0, 120, 64])
Chai has 40mg of caffeine.
Decaf has 0mg of caffeine.
Drip has 120mg of caffeine.
Espresso has 64mg of caffeine.


In [2]:
# use pass as a placeholder
def SomeFunction():
    pass


In [5]:
city_dict = {"Portland": {"Name": "Portland", "State": "Oregon", "Population": 500000}}
city_dict.update({"Chicago": {"Name": "Chicago", "State": "Illinois", "Population": 5000000}})
print(city_dict)
print(city_dict["Portland"])

{'Portland': {'Name': 'Portland', 'State': 'Oregon', 'Population': 500000}, 'Chicago': {'Name': 'Chicago', 'State': 'Illinois', 'Population': 5000000}}
{'Name': 'Portland', 'State': 'Oregon', 'Population': 500000}


In [13]:
import numpy as np
import pandas as pd

some_ndarray = np.array([1,2,3,4,5])
print(some_ndarray - 1)

list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
list3 = (list1, list2)
array1 = np.array(list3)
print(array1)

series1 = pd.Series(list1, index = list2)
print(series1)

dataf = pd.DataFrame([
    ['John', 'Doe', 12],
    ['Jane', 'Doe', 14],
    ['Oscar', 'Grouch', 57]
], columns = ['FirstName', 'LastName', 'Age']).set_index('FirstName')
print(dataf)


[0 1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
5    1
6    2
7    3
8    4
dtype: int64
          LastName  Age
FirstName              
John           Doe   12
Jane           Doe   14
Oscar       Grouch   57


In [5]:
import numpy as np
import pandas as pd

some_ndarray = np.array([1,2,3,4,5])
print(some_ndarray.shape)
print(some_ndarray[:-2])

empty_array = np.empty(2)
print(empty_array)

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np.shape(a))

(5,)
[1 2 3]
[2.05833592e-312 2.33419537e-312]
(3, 4)


In [3]:
import numpy as np
import pandas as pd

l = [["a", 12, 12], [None, 12.3, 33.], ["b", 12.3, 123], ["a", 1, 1]]
df = pd.DataFrame(l, columns=["a", "b", "c"])

print(df)

      a     b      c
0     a  12.0   12.0
1  None  12.3   33.0
2     b  12.3  123.0
3     a   1.0    1.0


In [ ]:
# Data cleaning stuff.  See also note in EN.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import codecademylib3_seaborn
import glob as glob

# The files imported here were on Codecademy
file_names = glob.glob('states[0-9].csv')
df_list = []
for file in file_names:
  df = pd.read_csv(file)
  df_list.append(df)

us_census = pd.concat(df_list)
us_census = us_census.drop_duplicates()

us_census['Income'] = us_census['Income'].replace('[\$]', '', regex=True)

us_census['male_female'] = us_census['GenderPop'].str.split('_')
us_census['male_pop'] = us_census.male_female.str.get(0)
us_census['female_pop'] = us_census.male_female.str.get(1)
us_census['male_pop'] = us_census.male_pop.replace('M', '', regex=True)
us_census['female_pop'] = us_census.female_pop.replace('F', '', regex=True)
us_census['Income'] = pd.to_numeric(us_census['Income'])
us_census['male_pop'] = pd.to_numeric(us_census['male_pop'])
us_census['female_pop'] = pd.to_numeric(us_census['female_pop'])

# plt.scatter(us_census.female_pop, us_census['Income'])
# plt.show()

print(us_census.columns)
us_census = us_census.fillna(value={"female_pop":(us_census["TotalPop"] - us_census["male_pop"])})
# print(us_census.female_pop)

us_census['Hispanic'] = us_census['Hispanic'].replace('[\%]', '', regex=True)
us_census['Hispanic'] = pd.to_numeric(us_census['Hispanic'])
print(us_census.dtypes)
plt.hist(us_census["Hispanic"])
plt.show()