In [1]:
drinks = ["espresso", "chai", "decaf", "drip"]
caffeine = [64, 40, 0, 120]
zipped_drinks = list(zip(drinks, caffeine))
print(zipped_drinks)
drinks_dict = {drink:caff for drink, caff in zipped_drinks}
print(drinks_dict)
print(list(drinks_dict))
print(drinks_dict.keys())
print(drinks_dict.get("espresso"))
espresso = drinks_dict.pop("espresso", "NA")
print(espresso)
print(drinks_dict)
drinks_dict.update({"espresso": espresso})
print(sorted(drinks_dict))
print(drinks_dict.values())
for drinks, caffeines in drinks_dict.items():
    print("{drink} has {caffeine}mg of caffeine.".format(drink=drinks.title(), caffeine=caffeines))


[('espresso', 64), ('chai', 40), ('decaf', 0), ('drip', 120)]
{'espresso': 64, 'chai': 40, 'decaf': 0, 'drip': 120}
['espresso', 'chai', 'decaf', 'drip']
dict_keys(['espresso', 'chai', 'decaf', 'drip'])
64
64
{'chai': 40, 'decaf': 0, 'drip': 120}
['chai', 'decaf', 'drip', 'espresso']
dict_values([40, 0, 120, 64])
Chai has 40mg of caffeine.
Decaf has 0mg of caffeine.
Drip has 120mg of caffeine.
Espresso has 64mg of caffeine.


In [2]:
# use pass as a placeholder
def SomeFunction():
    pass


In [5]:
city_dict = {"Portland": {"Name": "Portland", "State": "Oregon", "Population": 500000}}
city_dict.update({"Chicago": {"Name": "Chicago", "State": "Illinois", "Population": 5000000}})
print(city_dict)
print(city_dict["Portland"])

{'Portland': {'Name': 'Portland', 'State': 'Oregon', 'Population': 500000}, 'Chicago': {'Name': 'Chicago', 'State': 'Illinois', 'Population': 5000000}}
{'Name': 'Portland', 'State': 'Oregon', 'Population': 500000}


In [13]:
import numpy as np
import pandas as pd

some_ndarray = np.array([1,2,3,4,5])
print(some_ndarray - 1)

list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
list3 = (list1, list2)
array1 = np.array(list3)
print(array1)

series1 = pd.Series(list1, index = list2)
print(series1)

dataf = pd.DataFrame([
    ['John', 'Doe', 12],
    ['Jane', 'Doe', 14],
    ['Oscar', 'Grouch', 57]
], columns = ['FirstName', 'LastName', 'Age']).set_index('FirstName')
print(dataf)


[0 1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
5    1
6    2
7    3
8    4
dtype: int64
          LastName  Age
FirstName              
John           Doe   12
Jane           Doe   14
Oscar       Grouch   57


In [5]:
import numpy as np
import pandas as pd

some_ndarray = np.array([1,2,3,4,5])
print(some_ndarray.shape)
print(some_ndarray[:-2])

empty_array = np.empty(2)
print(empty_array)

a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np.shape(a))

(5,)
[1 2 3]
[2.05833592e-312 2.33419537e-312]
(3, 4)


NameError: name 'np' is not defined